const headerWidth = 30
const border = '='.repeat(headerWidth)

const headerLines = [border, 'Autogenerated code', 'Do not modify!', border]

const expandLine = expand(headerWidth, ' ')

const header = headerLines.map(line => `// |${expandLine(line)}|`).join('\n')
console.log(header)
/// prints
/// |==============================|
/// |      Autogenerated code      |
/// |        Do not modify!        |
/// |==============================|
