name: Next.js Cache
description: Cache for the Next.js build
runs:
  using: 'composite'
  steps:
    - uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/pkg/common-fp-org/.next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('./pnpm-lock.yaml') }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('./pnpm-lock.yaml') }}-
