name: Validate Monorepo State

on:
  workflow_dispatch:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  validate-monorepo-state:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - uses: ./.github/actions/next-cache
      - uses: ./.github/actions/turbo-cache
      - uses: ./.github/actions/tstyche-cache
      - run: pnpm install && pnpm validate
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: 'test-results'
          path: './test-results/'
